import type {
  Hotel,
  Restaurant,
  Cafe,
  Attraction,
  EventItem,
  Article,
  Destination,
  MapPoint,
} from "@/types";
import { placeholderImage } from "./placeholder-image";

// Every image below is a clearly-labeled placeholder (see lib/placeholder-image.ts)
// rather than a generic stock photo — swap each `coverImage`/`image`/`url`
// string for a real photo once you have one. This is sample content only;
// once Supabase is connected, real listings replace all of this (see lib/data/*).

export const destinations: Destination[] = [
  {
    id: "d1",
    slug: "downtown-hargeisa",
    name: "Downtown Hargeisa",
    description: "The commercial heart of the city — markets, banks, and street life.",
    image: placeholderImage("Downtown Hargeisa", { tone: "primary" }),
    placeCount: 48,
  },
  {
    id: "d2",
    slug: "war-memorial-district",
    name: "War Memorial District",
    description: "Home to the MiG monument and the Freedom Park gardens.",
    image: placeholderImage("War Memorial District", { tone: "secondary" }),
    placeCount: 12,
  },
  {
    id: "d3",
    slug: "hargeisa-suburbs",
    name: "Hargeisa Suburbs",
    description: "Quiet residential neighborhoods with new cafes and guesthouses.",
    image: placeholderImage("Hargeisa Suburbs", { tone: "accent" }),
    placeCount: 21,
  },
];

// Real, independently-operating hotels in Hargeisa, researched from public
// sources (official hotel sites, Tripadvisor, Booking.com, Facebook/Instagram
// business pages) in July 2026. Descriptions below are written fresh from
// those verified facts, not copied from any listing site. Fields we could
// not verify from a public source (phone, website, exact amenities) are left
// blank rather than guessed. Coordinates are best-effort placements based on
// the venue's known road/neighborhood, not precise GPS pins, since exact
// geocoding wasn't publicly available for most of these.
export const hotels: Hotel[] = [
  {
    id: "h1",
    slug: "ambassador-hotel-hargeisa",
    name: "Ambassador Hotel Hargeisa",
    shortDescription: "Upscale business hotel on Airport Road, close to Hargeisa International Airport.",
    description:
      "Ambassador Hotel Hargeisa is a business-oriented hotel on Airport Road, a short drive from Hargeisa International Airport. It's geared toward corporate travelers, with conference facilities and event space alongside standard guest rooms.",
    coverImage: placeholderImage("Ambassador Hotel Hargeisa"),
    gallery: [{ url: placeholderImage("Ambassador Hotel Hargeisa"), alt: "Ambassador Hotel Hargeisa" }],
    address: "Airport Road, Hargeisa, Somaliland",
    location: { lat: 9.519, lng: 44.087 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "+2522566666",
    website: "https://www.ambassadorhotelhargeisa.com",
    priceRange: "$$$",
    amenities: ["Conference Facilities", "Event Space", "Free WiFi"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h2",
    slug: "maamuus-hotel",
    name: "Maamuus Hotel",
    shortDescription: "Established hotel on Road No. 1, minutes from downtown Hargeisa.",
    description:
      "Maamuus Hotel sits on Road No. 1's east side next to the Hargeisa traffic police headquarters, about five minutes from downtown and twenty minutes from the airport. It's one of the longer-standing hotel names in the city.",
    coverImage: placeholderImage("Maamuus Hotel"),
    gallery: [{ url: placeholderImage("Maamuus Hotel"), alt: "Maamuus Hotel" }],
    address: "Road No. 1 (East Side), near Traffic Police HQ, Hargeisa, Somaliland",
    location: { lat: 9.561, lng: 44.063 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    website: "http://www.maamuushotelhargeisa.com",
    priceRange: "$$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h3",
    slug: "alijirde-hotel",
    name: "Alijirde Hotel",
    shortDescription: "Hotel on Gabahaddi Road with its own in-house restaurant, Zaytuun.",
    description:
      "Alijirde Hotel is located on Gabahaddi Road and operates its own in-house restaurant, Zaytuun, serving traditional Somali dishes. Reservations for rooms and the restaurant are handled through separate lines.",
    coverImage: placeholderImage("Alijirde Hotel"),
    gallery: [{ url: placeholderImage("Alijirde Hotel"), alt: "Alijirde Hotel" }],
    address: "Gabahaddi Rd, Hargeisa, Somaliland",
    location: { lat: 9.558, lng: 44.061 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "523785",
    website: "https://alijirdehotel.com",
    priceRange: "$$",
    amenities: ["On-site Restaurant"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h4",
    slug: "serene-sarovar-premiere-hargeisa",
    name: "Serene Sarovar Premiere Hargeisa",
    shortDescription: "5-star hotel from the Sarovar Hotels chain, overlooking the city near the airport.",
    description:
      "Serene Sarovar Premiere Hargeisa is a 5-star property from the India-based Sarovar Hotels & Resorts chain, one of the newest upscale hotels in the city. It sits on high ground overlooking Hargeisa, about five minutes from the airport, with a restaurant, fitness centre, garden and airport shuttle.",
    coverImage: placeholderImage("Serene Sarovar Premiere Hargeisa"),
    gallery: [{ url: placeholderImage("Serene Sarovar Premiere Hargeisa"), alt: "Serene Sarovar Premiere Hargeisa" }],
    address: "Near Hargeisa International Airport, Hargeisa, Somaliland",
    location: { lat: 9.516, lng: 44.084 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    website: "https://www.sarovarhotels.com/serene-premiere-hargeisa/",
    priceRange: "$$$$",
    amenities: ["Restaurant", "Fitness Centre", "Garden", "Airport Shuttle", "Free WiFi"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h5",
    slug: "jees-hotel",
    name: "Jees Hotel",
    shortDescription: "Mid-range hotel with a restaurant, bar, and shared terrace lounge.",
    description:
      "Jees Hotel offers a restaurant, bar, garden and shared terrace lounge alongside its guest rooms, and is bookable through major international hotel platforms.",
    coverImage: placeholderImage("Jees Hotel"),
    gallery: [{ url: placeholderImage("Jees Hotel"), alt: "Jees Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.556, lng: 44.069 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: ["Restaurant", "Bar", "Garden", "Shared Lounge", "Fitness Centre"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h6",
    slug: "damal-hotel-hargeisa",
    name: "Damal Hotel Hargeisa",
    shortDescription: "Downtown-area hotel with its own restaurant on the Waheen Highway corridor.",
    description:
      "Damal Hotel Hargeisa is located along the Waheen Highway 2 corridor and runs an attached restaurant serving Somali dishes to both guests and walk-in diners.",
    coverImage: placeholderImage("Damal Hotel Hargeisa"),
    gallery: [{ url: placeholderImage("Damal Hotel Hargeisa"), alt: "Damal Hotel Hargeisa" }],
    address: "Waheen Highway 2, Hargeisa, Somaliland",
    location: { lat: 9.572, lng: 44.058 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: ["On-site Restaurant"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h7",
    slug: "gulf-star-hotel",
    name: "Gulf Star Hotel",
    shortDescription: "3-star hotel offering round-the-clock front desk service and free WiFi.",
    description:
      "Gulf Star Hotel is a 3-star property offering room service, a 24-hour front desk and free WiFi, with an attached restaurant.",
    coverImage: placeholderImage("Gulf Star Hotel"),
    gallery: [{ url: placeholderImage("Gulf Star Hotel"), alt: "Gulf Star Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.553, lng: 44.073 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: ["Room Service", "24-Hour Front Desk", "Free WiFi", "On-site Restaurant"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h8",
    slug: "maan-soor-hotel",
    name: "Maan-Soor Hotel",
    shortDescription: "Long-running Hargeisa hotel, part of the wider Maan-Soor hotel group.",
    description:
      "Maan-Soor Hotel is the Hargeisa property of the Maan-Soor hotel group, one of the better-known hospitality names operating across Somaliland.",
    coverImage: placeholderImage("Maan-Soor Hotel"),
    gallery: [{ url: placeholderImage("Maan-Soor Hotel"), alt: "Maan-Soor Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.565, lng: 44.071 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    website: "https://maan-soor.com/hargeisa/",
    priceRange: "$$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h9",
    slug: "safari-hotel-hargeisa",
    name: "Safari Hotel",
    shortDescription: "Well-known Hargeisa hotel with a long-standing presence in the city.",
    description:
      "Safari Hotel is one of Hargeisa's established hotel names, popular with both local and visiting guests.",
    coverImage: placeholderImage("Safari Hotel Hargeisa"),
    gallery: [{ url: placeholderImage("Safari Hotel Hargeisa"), alt: "Safari Hotel Hargeisa" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.560, lng: 44.068 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "+252637111111",
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h10",
    slug: "oriental-hotel-hargeisa",
    name: "Oriental Hotel",
    shortDescription: "Hotel in the heart of Hargeisa offering a central base for visitors.",
    description: "Oriental Hotel is centrally located in Hargeisa, offering straightforward accommodation for business and leisure travelers.",
    coverImage: placeholderImage("Oriental Hotel Hargeisa"),
    gallery: [{ url: placeholderImage("Oriental Hotel Hargeisa"), alt: "Oriental Hotel Hargeisa" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.562, lng: 44.064 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h11",
    slug: "bandare-hotel",
    name: "Bandare Hotel",
    shortDescription: "Newer hotel and restaurant on the Berbera road in New Hargeisa.",
    description:
      "Bandare Hotel is a newer property on the road toward Berbera, in the New Hargeisa area, combining guest rooms with an on-site restaurant and airport shuttle service arranged through reception.",
    coverImage: placeholderImage("Bandare Hotel"),
    gallery: [{ url: placeholderImage("Bandare Hotel"), alt: "Bandare Hotel" }],
    address: "Berbera Road, New Hargeisa, Somaliland",
    location: { lat: 9.548, lng: 44.11 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    website: "https://www.bandarehotel.com",
    priceRange: "$$",
    amenities: ["On-site Restaurant", "Airport Shuttle"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h12",
    slug: "dhoolayare-hotel",
    name: "Dhoolayare Hotel",
    shortDescription: "Newer hotel in Hargeisa combining lodging with Somali dining.",
    description: "Dhoolayare Hotel is a newer addition to Hargeisa's hotel scene, pairing guest rooms with a Somali-cuisine dining room.",
    coverImage: placeholderImage("Dhoolayare Hotel"),
    gallery: [{ url: placeholderImage("Dhoolayare Hotel"), alt: "Dhoolayare Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.567, lng: 44.075 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: ["On-site Restaurant"],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h13",
    slug: "hargeisa-club-hotel",
    name: "Hargeisa Club",
    shortDescription: "Hotel offering comfort and easy access to the city center.",
    description: "Hargeisa Club is a hotel property offering convenient access to central Hargeisa for both local and visiting guests.",
    coverImage: placeholderImage("Hargeisa Club Hotel"),
    gallery: [{ url: placeholderImage("Hargeisa Club Hotel"), alt: "Hargeisa Club Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.559, lng: 44.062 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h14",
    slug: "carro-edeg-hotel",
    name: "Carro Edeg Hotel",
    shortDescription: "Hargeisa hotel listed among the city's mid-range lodging options.",
    description: "Carro Edeg Hotel is one of Hargeisa's mid-range hotels, offering standard guest room accommodation in the city.",
    coverImage: placeholderImage("Carro Edeg Hotel"),
    gallery: [{ url: placeholderImage("Carro Edeg Hotel"), alt: "Carro Edeg Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.564, lng: 44.072 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h15",
    slug: "assod-hotel",
    name: "Assod Hotel",
    shortDescription: "One of Hargeisa's recognized hotel names for business and leisure stays.",
    description: "Assod Hotel is a recognized name among Hargeisa's hotel options, serving both business and leisure travelers.",
    coverImage: placeholderImage("Assod Hotel"),
    gallery: [{ url: placeholderImage("Assod Hotel"), alt: "Assod Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.557, lng: 44.079 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h16",
    slug: "beder-hotel",
    name: "Beder Hotel",
    shortDescription: "Hargeisa hotel offering standard accommodation in the city.",
    description: "Beder Hotel offers standard guest accommodation in Hargeisa, catering to both local and out-of-town visitors.",
    coverImage: placeholderImage("Beder Hotel"),
    gallery: [{ url: placeholderImage("Beder Hotel"), alt: "Beder Hotel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.551, lng: 44.066 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h17",
    slug: "hayat-hotel-hargeisa",
    name: "Hayat Hotel",
    shortDescription: "Hargeisa hotel offering guest rooms in the wider downtown area.",
    description: "Hayat Hotel provides guest room accommodation in Hargeisa's wider downtown area.",
    coverImage: placeholderImage("Hayat Hotel Hargeisa"),
    gallery: [{ url: placeholderImage("Hayat Hotel Hargeisa"), alt: "Hayat Hotel Hargeisa" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.566, lng: 44.06 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
  {
    id: "h18",
    slug: "hadhwanaag-hotel",
    name: "Hadhwanaag Hotel",
    shortDescription: "One of Hargeisa's older, historic hotels, downtown near the MiG Monument.",
    description:
      "Hadhwanaag Hotel is one of the more historic hotel names in Hargeisa, located downtown within walking distance of the MiG Monument and Freedom Park.",
    coverImage: placeholderImage("Hadhwanaag Hotel"),
    gallery: [{ url: placeholderImage("Hadhwanaag Hotel"), alt: "Hadhwanaag Hotel" }],
    address: "Downtown Hargeisa, near MiG Monument, Somaliland",
    location: { lat: 9.561, lng: 44.0655 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    priceRange: "$$",
    amenities: [],
    nearbyAttractionIds: [],
    featured: false,
    languages: [],
    rooms: [],
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "r1",
    slug: "sultan-restaurant",
    name: "Sultan Restaurant",

    shortDescription:
      "One of Hargeisa's most popular restaurants serving Somali, Arabic and seafood cuisine.",

    description:
      "Sultan Restaurant is one of the best-known dining destinations in Hargeisa. It offers Somali, Arabic, grilled and seafood dishes in a modern and family-friendly atmosphere. The restaurant is popular with locals, business travelers and tourists visiting Somaliland.",

    // ⬇️ ضعها هنا
    coverImage: "/images/restaurants/sultan/hero.jpeg",

    gallery: [
      {
        url: "/images/restaurants/sultan/1.jpeg",
        alt: "Sultan Restaurant",
      },
      {
        url: "/images/restaurants/sultan/2.jpeg",
        alt: "Dining Area",
      },
      {
        url: "/images/restaurants/sultan/3.jpeg",
        alt: "Food",
      },
      {
        url: "/images/restaurants/sultan/4.jpeg",
        alt: "Outdoor Seating",
      },
      {
        url: "/images/restaurants/sultan/5.jpeg",
        alt: "Restaurant Interior",
      },
      {
        url: "/images/restaurants/sultan/6.jpeg",
        alt: "Signature Dishes",
      },
    ],

    address: "Jigjiga Yar, Hargeisa, Somaliland",

location: {
  lat: 9.5624,
  lng: 44.0659,
},

rating: 4.8,
reviewCount: 250,

reviews: [],

cuisine: [
  "Somali",
  "Arabic",
  "BBQ",
  "Seafood"
],

priceRange: "$$",

openingHours: "8:00 AM – 11:00 PM",

menuHighlights: [
  {
    name: "Mixed Grill",
    price: "$12",
    description: "Mixed grilled meat with rice and fresh salad."
  },
  {
    name: "Fish Fillet",
    price: "$10"
  },
  {
    name: "Chicken Steak",
    price: "$9"
  }
],

reservable: true,

featured: false,
  },

  // Real, independently-operating restaurants in Hargeisa, researched from
  // public sources (Tripadvisor, Facebook business pages, restaurant
  // websites) in July 2026. Descriptions are original, written from those
  // verified facts. No rating/review numbers are carried over from other
  // platforms — rating/reviewCount stay at 0 until real Go Hargeisa users
  // leave reviews. Coordinates are best-effort placements by known
  // road/neighborhood, not precise GPS pins.
  {
    id: "r2",
    slug: "damal-restaurant",
    name: "Damal Restaurant",
    shortDescription: "Somali-cuisine restaurant on the Waheen Highway corridor.",
    description:
      "Damal Restaurant serves Somali dishes along the Waheen Highway 2 corridor, attached to the Damal Hotel and open to walk-in diners as well as hotel guests.",
    coverImage: placeholderImage("Damal Restaurant"),
    gallery: [{ url: placeholderImage("Damal Restaurant"), alt: "Damal Restaurant" }],
    address: "Waheen Highway 2, Hargeisa, Somaliland",
    location: { lat: 9.572, lng: 44.058 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r3",
    slug: "summertime-restaurant",
    name: "Summertime Restaurant",
    shortDescription: "Popular Somali restaurant on Gollis University Road.",
    description:
      "Summertime Restaurant is a well-known dining spot on Gollis University Road, regularly mentioned among Hargeisa's more upscale Somali-cuisine options.",
    coverImage: placeholderImage("Summertime Restaurant"),
    gallery: [{ url: placeholderImage("Summertime Restaurant"), alt: "Summertime Restaurant" }],
    address: "Gollis University Road, Hargeisa, Somaliland",
    location: { lat: 9.548, lng: 44.078 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r4",
    slug: "twenty-five-restaurant",
    name: "Twenty Five",
    shortDescription: "Somali restaurant on Jigjiga-Yar Road.",
    description: "Twenty Five is a Somali-cuisine restaurant on Jigjiga-Yar Road, in the same stretch as several of Hargeisa's better-known dining spots.",
    coverImage: placeholderImage("Twenty Five Restaurant"),
    gallery: [{ url: placeholderImage("Twenty Five Restaurant"), alt: "Twenty Five Restaurant" }],
    address: "Jigjiga-Yar Rd, Hargeisa, Somaliland",
    location: { lat: 9.562, lng: 44.0665 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r5",
    slug: "rose-restaurant",
    name: "Rose Restaurant",
    shortDescription: "Somali restaurant on Jigjiga-Yar Road known for a warm atmosphere.",
    description: "Rose Restaurant serves Somali cuisine on Jigjiga-Yar Road, known locally for a warm, welcoming dining room.",
    coverImage: placeholderImage("Rose Restaurant"),
    gallery: [{ url: placeholderImage("Rose Restaurant"), alt: "Rose Restaurant" }],
    address: "Jigjiga-Yar Rd, Hargeisa, Somaliland",
    location: { lat: 9.5615, lng: 44.0668 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r6",
    slug: "caawiye-hotel-cafe",
    name: "Caawiye Hotel & Cafe",
    shortDescription: "Restaurant on Hero Awr Road known for biryani and Indian-influenced dishes.",
    description: "Caawiye Hotel & Cafe, on Hero Awr Road, is known for biryani and other Indian-influenced dishes alongside its regular menu.",
    coverImage: placeholderImage("Caawiye Hotel & Cafe"),
    gallery: [{ url: placeholderImage("Caawiye Hotel & Cafe"), alt: "Caawiye Hotel & Cafe" }],
    address: "Hero Awr Road, Hargeisa, Somaliland",
    location: { lat: 9.555, lng: 44.072 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Indian", "Biryani"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r7",
    slug: "o2-restaurant-and-cafe",
    name: "O2 Restaurant and Cafe",
    shortDescription: "Restaurant and cafe serving Somali dishes.",
    description: "O2 Restaurant and Cafe serves Somali dishes in a combined restaurant-and-cafe format.",
    coverImage: placeholderImage("O2 Restaurant and Cafe"),
    gallery: [{ url: placeholderImage("O2 Restaurant and Cafe"), alt: "O2 Restaurant and Cafe" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5605, lng: 44.0645 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r8",
    slug: "jumeira-restaurant-cafe-lounge",
    name: "Jumeira Restaurant, Café & Lounge",
    shortDescription: "Restaurant, café and lounge on Sacadadiin Road mixing local and international dishes.",
    description: "Jumeira Restaurant, Café & Lounge on Sacadadiin Road combines a restaurant, café and lounge in one venue, mixing Somali and international dishes.",
    coverImage: placeholderImage("Jumeira Restaurant Cafe & Lounge"),
    gallery: [{ url: placeholderImage("Jumeira Restaurant Cafe & Lounge"), alt: "Jumeira Restaurant Cafe & Lounge" }],
    address: "Sacadadiin Rd, Hargeisa, Somaliland",
    location: { lat: 9.565, lng: 44.068 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali", "International"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r9",
    slug: "hayaat-restaurant",
    name: "Hayaat Restaurant",
    shortDescription: "Restaurant known for authentic Somali flavors.",
    description: "Hayaat Restaurant is known among locals for authentic Somali cooking.",
    coverImage: placeholderImage("Hayaat Restaurant"),
    gallery: [{ url: placeholderImage("Hayaat Restaurant"), alt: "Hayaat Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.558, lng: 44.07 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r10",
    slug: "zaytuun-restaurant",
    name: "Zaytuun Restaurant",
    shortDescription: "Somali-cuisine restaurant attached to Alijirde Hotel on Gabahaddi Road.",
    description: "Zaytuun Restaurant is the in-house dining room of Alijirde Hotel on Gabahaddi Road, specializing in traditional Somali stews and freshly baked bread.",
    coverImage: placeholderImage("Zaytuun Restaurant"),
    gallery: [{ url: placeholderImage("Zaytuun Restaurant"), alt: "Zaytuun Restaurant" }],
    address: "Gabahaddi Rd, Hargeisa, Somaliland",
    location: { lat: 9.558, lng: 44.061 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "523784",
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r11",
    slug: "gol-jano-restaurant",
    name: "Gol-jano Restaurant",
    shortDescription: "Somali restaurant known for camel meat (hilib geel) dishes.",
    description: "Gol-jano Restaurant, on Wadada Muj. Adan Cadde, is known for traditional Somali dishes built around camel meat (hilib geel).",
    coverImage: placeholderImage("Gol-jano Restaurant"),
    gallery: [{ url: placeholderImage("Gol-jano Restaurant"), alt: "Gol-jano Restaurant" }],
    address: "Wadada Muj. Adan Cadde, Hargeisa, Somaliland",
    location: { lat: 9.5635, lng: 44.0685 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r12",
    slug: "yusuf-cadaani-restaurant",
    name: "Yusuf Cadaani Restaurant",
    shortDescription: "Somali restaurant open from late afternoon until dawn.",
    description: "Yusuf Cadaani Restaurant serves authentic Somali cuisine, notable for staying open from late afternoon until dawn.",
    coverImage: placeholderImage("Yusuf Cadaani Restaurant"),
    gallery: [{ url: placeholderImage("Yusuf Cadaani Restaurant"), alt: "Yusuf Cadaani Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5655, lng: 44.073 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "Late afternoon – dawn",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r13",
    slug: "maandeeq-restaurant",
    name: "Maandeeq Restaurant",
    shortDescription: "One of Hargeisa's few Chinese-cuisine restaurants.",
    description: "Maandeeq Restaurant is one of the small number of Chinese-cuisine restaurants operating in Hargeisa.",
    coverImage: placeholderImage("Maandeeq Restaurant"),
    gallery: [{ url: placeholderImage("Maandeeq Restaurant"), alt: "Maandeeq Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.554, lng: 44.065 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Chinese"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r14",
    slug: "sarkalam-restaurant",
    name: "Sarkalam Restaurant",
    shortDescription: "Ethiopian-cuisine restaurant in Hargeisa.",
    description: "Sarkalam Restaurant serves authentic Ethiopian cuisine, one of a handful of dedicated Ethiopian dining spots in the city.",
    coverImage: placeholderImage("Sarkalam Restaurant"),
    gallery: [{ url: placeholderImage("Sarkalam Restaurant"), alt: "Sarkalam Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5665, lng: 44.0615 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Ethiopian"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r15",
    slug: "one4seven-restaurant",
    name: "One4Seven Restaurant",
    shortDescription: "Rooftop lounge and fine-dining restaurant in Rugsan Gardens, Masalaha.",
    description:
      "One4Seven Restaurant is a rooftop lounge and fine-dining venue in Rugsan Gardens, opposite Sheikh Mustafa Mosque in the Masalaha area, offering dine-in, delivery and takeout with city views.",
    coverImage: placeholderImage("One4Seven Restaurant"),
    gallery: [{ url: placeholderImage("One4Seven Restaurant"), alt: "One4Seven Restaurant" }],
    address: "Rugsan Gardens, opposite Sheikh Mustafa Mosque, Masalaha, Hargeisa, Somaliland",
    location: { lat: 9.545, lng: 44.073 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "+252638450755",
    cuisine: ["Somali", "International"],
    priceRange: "$$$",
    openingHours: "7:00 AM – 11:30 PM",
    menuHighlights: [],
    reservable: true,
    featured: false,
  },
  {
    id: "r16",
    slug: "four-seasons-restaurant",
    name: "Four Seasons Restaurant",
    shortDescription: "Somali-cuisine restaurant among Hargeisa's more upscale dining picks.",
    description: "Four Seasons Restaurant serves Somali cuisine and is regularly named among Hargeisa's more upscale dining options.",
    coverImage: placeholderImage("Four Seasons Restaurant"),
    gallery: [{ url: placeholderImage("Four Seasons Restaurant"), alt: "Four Seasons Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5595, lng: 44.0625 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r17",
    slug: "gulf-star-restaurant",
    name: "Gulf Star Restaurant",
    shortDescription: "Restaurant attached to Gulf Star Hotel.",
    description: "Gulf Star Restaurant is the dining room attached to Gulf Star Hotel, open to both hotel guests and walk-in diners.",
    coverImage: placeholderImage("Gulf Star Restaurant"),
    gallery: [{ url: placeholderImage("Gulf Star Restaurant"), alt: "Gulf Star Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.553, lng: 44.073 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Somali"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r18",
    slug: "al-habasha-restaurant",
    name: "Al Habasha Restaurant",
    shortDescription: "Ethiopian/Habesha-cuisine restaurant in Hargeisa.",
    description: "Al Habasha Restaurant specializes in Ethiopian (Habesha) cuisine.",
    coverImage: placeholderImage("Al Habasha Restaurant"),
    gallery: [{ url: placeholderImage("Al Habasha Restaurant"), alt: "Al Habasha Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5515, lng: 44.0705 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Ethiopian"],
    priceRange: "$$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r19",
    slug: "creams-fast-food",
    name: "Creams Fast Food",
    shortDescription: "Pizza and fast-food restaurant in the Jigjigyare area.",
    description: "Creams Fast Food has served pizza and fast food from the Jigjigyare area since 2016, a short walk from Summertime Restaurant.",
    coverImage: placeholderImage("Creams Fast Food"),
    gallery: [{ url: placeholderImage("Creams Fast Food"), alt: "Creams Fast Food" }],
    address: "Jigjigyare, Hargeisa, Somaliland",
    location: { lat: 9.5485, lng: 44.0775 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Fast Food", "Pizza"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r20",
    slug: "mega-plaza-eatery",
    name: "Mega Plaza Eatery",
    shortDescription: "Restaurant serving African and pizza dishes.",
    description: "Mega Plaza Eatery serves a mix of African and pizza dishes in Hargeisa.",
    coverImage: placeholderImage("Mega Plaza Eatery"),
    gallery: [{ url: placeholderImage("Mega Plaza Eatery"), alt: "Mega Plaza Eatery" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5575, lng: 44.0745 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["African", "Pizza"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r21",
    slug: "adams-restaurant-cafe",
    name: "Adams Restaurant & Cafe",
    shortDescription: "Combined restaurant and cafe serving pizza.",
    description: "Adams Restaurant & Cafe combines a cafe with a pizza-focused restaurant menu.",
    coverImage: placeholderImage("Adams Restaurant & Cafe"),
    gallery: [{ url: placeholderImage("Adams Restaurant & Cafe"), alt: "Adams Restaurant & Cafe" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5645, lng: 44.0595 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Pizza", "Cafe"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r22",
    slug: "al-yemen-al-saeed-restaurant",
    name: "Al Yemen Al Saeed Restaurant",
    shortDescription: "Restaurant and fast food spot serving Yemeni cuisine.",
    description: "Al Yemen Al Saeed Restaurant serves Yemeni cuisine alongside a fast-food menu.",
    coverImage: placeholderImage("Al Yemen Al Saeed Restaurant"),
    gallery: [{ url: placeholderImage("Al Yemen Al Saeed Restaurant"), alt: "Al Yemen Al Saeed Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5605, lng: 44.0715 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Yemeni", "Fast Food"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r23",
    slug: "primo-gelato-and-fast-food",
    name: "Primo Gelato And Fast Food",
    shortDescription: "Gelato and fast-food spot in Hargeisa.",
    description: "Primo Gelato And Fast Food offers gelato alongside a fast-food menu.",
    coverImage: placeholderImage("Primo Gelato And Fast Food"),
    gallery: [{ url: placeholderImage("Primo Gelato And Fast Food"), alt: "Primo Gelato And Fast Food" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5555, lng: 44.0635 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Fast Food", "Dessert"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r24",
    slug: "arab-vibes",
    name: "Arab Vibes",
    shortDescription: "Burger, pizza and fried chicken spot in Jigjigyare, next to Hanad Hospital.",
    description: "Arab Vibes, in Jigjigyare next to Hanad Hospital and across from Indho Birta supermarket, serves burgers, pizza and fried chicken.",
    coverImage: placeholderImage("Arab Vibes"),
    gallery: [{ url: placeholderImage("Arab Vibes"), alt: "Arab Vibes" }],
    address: "Jigjigyare, next to Hanad Hospital, Hargeisa, Somaliland",
    location: { lat: 9.549, lng: 44.076 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Fast Food", "Burgers", "Pizza"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
  {
    id: "r25",
    slug: "khan-fast-food",
    name: "Khan Fast Food",
    shortDescription: "Fast-food restaurant known for shawarma and burgers.",
    description: "Khan Fast Food serves shawarma, burgers and other fast-food staples.",
    coverImage: placeholderImage("Khan Fast Food"),
    gallery: [{ url: placeholderImage("Khan Fast Food"), alt: "Khan Fast Food" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.563, lng: 44.078 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    cuisine: ["Fast Food", "Shawarma"],
    priceRange: "$",
    openingHours: "",
    menuHighlights: [],
    reservable: false,
    featured: false,
  },
];

// Real, independently-operating cafes in Hargeisa, researched from public
// sources (official sites, Tripadvisor, Facebook/Instagram business pages)
// in July 2026. Descriptions are original. rating/reviewCount start at 0 —
// no ratings are carried over from other platforms. Coordinates are
// best-effort placements by known road/neighborhood, not precise GPS pins.
export const cafes: Cafe[] = [
  {
    id: "c1",
    slug: "cup-of-art",
    name: "Cup of Art Coffee House",
    shortDescription: "Sister-and-brother-run coffee house popular with Hargeisa's expat community.",
    description:
      "Cup of Art Coffee House is run by a sister-and-brother team and has built a following among both locals and Hargeisa's expatriate community for its relaxed, art-filled interior.",
    coverImage: placeholderImage("Cup of Art Coffee House"),
    gallery: [{ url: placeholderImage("Cup of Art Coffee House"), alt: "Cup of Art Coffee House" }],
    address: "Pepsi District, Hargeisa, Somaliland",
    location: { lat: 9.5534, lng: 44.0612 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: true,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c2",
    slug: "cafe-barbera-hargeisa",
    name: "Café Barbera Hargeisa",
    shortDescription: "Italian coffee-house brand with over a century of history, inside Deero Mall.",
    description:
      "Café Barbera Hargeisa is the local branch of the century-old Italian coffee brand, located inside Deero Mall in the city centre. It's an air-conditioned, carpeted space known for its coffee and cake selection.",
    coverImage: placeholderImage("Cafe Barbera Hargeisa"),
    gallery: [{ url: placeholderImage("Cafe Barbera Hargeisa"), alt: "Cafe Barbera Hargeisa" }],
    address: "Deero Mall, Hargeisa, Somaliland",
    location: { lat: 9.56, lng: 44.064 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    phone: "+252653333520",
    specialDrinks: [],
    wifi: true,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c3",
    slug: "beydan-coffee",
    name: "Beydan Coffee",
    shortDescription: "Newer coffee shop in Wadaadiid Mall on Jigjiga Yar.",
    description:
      "Beydan Coffee is one of the newer coffee shops in Hargeisa, located in Wadaadiid Mall on Jigjiga Yar and positioned as a relaxed spot to sit and work.",
    coverImage: placeholderImage("Beydan Coffee"),
    gallery: [{ url: placeholderImage("Beydan Coffee"), alt: "Beydan Coffee" }],
    address: "Wadaadiid Mall, Jigjiga Yar, Hargeisa, Somaliland",
    location: { lat: 9.562, lng: 44.0665 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: true,
    workingSpace: true,
    openingHours: "Sat–Wed 7:00 AM–12:00 AM, Thu 7:00 AM–12:30 AM, Fri 1:00 PM–12:00 AM",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c4",
    slug: "mocha-cafe-house",
    name: "Mocha Cafe House",
    shortDescription: "Coffee, milkshakes and light bites near the city centre.",
    description:
      "Mocha Cafe House serves coffee, milkshakes, sandwiches and desserts, popular with both locals and visitors for its cozy seating.",
    coverImage: placeholderImage("Mocha Cafe House"),
    gallery: [{ url: placeholderImage("Mocha Cafe House"), alt: "Mocha Cafe House" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5598, lng: 44.0635 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: ["Milkshakes"],
    wifi: false,
    workingSpace: false,
    openingHours: "8:00 AM – 12:00 AM (Fri from 4:00 PM)",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c5",
    slug: "kings-cafe",
    name: "Kings Cafe",
    shortDescription: "Coffee shop known locally as one of Hargeisa's social hubs.",
    description: "Kings Cafe is a coffee spot that's become one of Hargeisa's regular social gathering points.",
    coverImage: placeholderImage("Kings Cafe"),
    gallery: [{ url: placeholderImage("Kings Cafe"), alt: "Kings Cafe" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5645, lng: 44.0705 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: false,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c6",
    slug: "cafe-laasgeel",
    name: "Café Laasgeel",
    shortDescription: "African-style cafe serving meals alongside coffee.",
    description: "Café Laasgeel is an African-style cafe serving full meals alongside its coffee menu.",
    coverImage: placeholderImage("Cafe Laasgeel"),
    gallery: [{ url: placeholderImage("Cafe Laasgeel"), alt: "Cafe Laasgeel" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5565, lng: 44.0685 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: false,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c7",
    slug: "harrar-coffeehouse-restaurant",
    name: "Harrar Coffeehouse & Restaurant",
    shortDescription: "Combined coffeehouse and restaurant serving African food and coffee.",
    description: "Harrar Coffeehouse & Restaurant pairs a full African-food restaurant menu with a dedicated coffee and tea program.",
    coverImage: placeholderImage("Harrar Coffeehouse & Restaurant"),
    gallery: [{ url: placeholderImage("Harrar Coffeehouse & Restaurant"), alt: "Harrar Coffeehouse & Restaurant" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5525, lng: 44.0655 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: false,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c8",
    slug: "time-out-cafe",
    name: "Time-out Café",
    shortDescription: "Family-dining cafe in Hargeisa.",
    description: "Time-out Café is geared toward family dining, serving a casual food and drinks menu.",
    coverImage: placeholderImage("Time-out Cafe"),
    gallery: [{ url: placeholderImage("Time-out Cafe"), alt: "Time-out Cafe" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5655, lng: 44.0625 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: false,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
  {
    id: "c9",
    slug: "kaah-coffee-shop",
    name: "Kaah Coffee Shop",
    shortDescription: "Coffee shop mentioned among Hargeisa's better-known coffee spots.",
    description: "Kaah Coffee Shop is regularly named alongside Hargeisa's other well-known coffee spots.",
    coverImage: placeholderImage("Kaah Coffee Shop"),
    gallery: [{ url: placeholderImage("Kaah Coffee Shop"), alt: "Kaah Coffee Shop" }],
    address: "Hargeisa, Somaliland",
    location: { lat: 9.5585, lng: 44.0675 },
    rating: 0,
    reviewCount: 0,
    reviews: [],
    specialDrinks: [],
    wifi: false,
    workingSpace: false,
    openingHours: "",
    menuHighlights: [],
    featured: false,
  },
];

export const attractions: Attraction[] = [
  {
    id: "a1",
    slug: "freedom-park-mig-monument",
    name: "Freedom Park & MiG Monument",
    shortDescription: "Iconic war memorial and fighter jet monument in the city center.",
    description:
      "The MiG Monument, mounted on a plinth in Freedom Park, commemorates the 1988 uprising and is one of the most photographed landmarks in Hargeisa.",
    coverImage: placeholderImage("Freedom Park & MiG Monument", { tone: "secondary" }),
    gallery: [{ url: placeholderImage("MiG Monument — Sunset"), alt: "Monument at sunset" }],
    address: "Freedom Park, Hargeisa",
    location: { lat: 9.5605, lng: 44.065 },
    rating: 4.6,
    reviewCount: 267,
    reviews: [],
    history:
      "The monument was erected to honor those who died during the Somaliland War of Independence, using an actual MiG-17 aircraft.",
    bestTimeToVisit: "Late afternoon, for golden-hour photos",
    entryFee: "Free",
    visitorTips: ["Best visited on foot", "Combine with a walk through the surrounding market"],
    nearbyRestaurantIds: ["r1"],
    nearbyHotelIds: ["h1"],
    category: "landmark",
    featured: true,
  },
  {
    id: "a2",
    slug: "waheen-market",
    name: "Waheen Market",
    shortDescription: "Somaliland's largest open-air market for textiles, spices and crafts.",
    description:
      "A sprawling, colorful market where you can find everything from hand-woven baskets to frankincense — a sensory introduction to daily life in Hargeisa.",
    coverImage: placeholderImage("Waheen Market", { tone: "accent" }),
    gallery: [{ url: placeholderImage("Waheen Market — Stalls") , alt: "Market stalls" }],
    address: "Waheen, Hargeisa",
    location: { lat: 9.5598, lng: 44.0705 },
    rating: 4.4,
    reviewCount: 143,
    reviews: [],
    history: "One of the oldest trading markets in the Horn of Africa, still central to the city's economy.",
    bestTimeToVisit: "Morning, before the midday heat",
    entryFee: "Free",
    visitorTips: ["Bargain respectfully", "Ask before photographing vendors"],
    nearbyRestaurantIds: [],
    nearbyHotelIds: ["h2"],
    category: "market",
  },
];

export const events: EventItem[] = [
  {
    id: "e1",
    slug: "hargeisa-international-book-fair",
    title: "Hargeisa International Book Fair",
    description: "East Africa's leading literary festival, bringing together writers from across the region.",
    coverImage: placeholderImage("Hargeisa International Book Fair"),
    category: "cultural",
    startDate: "2026-08-01",
    endDate: "2026-08-06",
    location: "Hargeisa Cultural Centre",
  },
  {
    id: "e2",
    slug: "somaliland-independence-day",
    title: "Somaliland Independence Day",
    description: "National celebrations with parades, music and fireworks across the city.",
    coverImage: placeholderImage("Somaliland Independence Day", { tone: "accent" }),
    category: "national",
    startDate: "2026-06-26",
    endDate: "2026-06-26",
    location: "Freedom Park",
  },
];

export const articles: Article[] = [
  {
    id: "b1",
    slug: "top-10-things-to-do-in-hargeisa",
    title: "Top 10 Things to Do in Hargeisa",
    excerpt: "From the MiG Monument to camel meat suqaar, here's how to spend your first days in the city.",
    coverImage: placeholderImage("Top 10 Things To Do"),
    author: "Go Hargeisa Editorial",
    publishedAt: "2026-06-10",
    readMinutes: 7,
    category: "Guides",
  },
  {
    id: "b2",
    slug: "best-restaurants-in-hargeisa",
    title: "The Best Restaurants in Hargeisa Right Now",
    excerpt: "Our editors' picks for grilled meat, seafood and the city's best cup of Somali tea.",
    coverImage: placeholderImage("Best Restaurants Guide", { tone: "secondary" }),
    author: "Go Hargeisa Editorial",
    publishedAt: "2026-05-22",
    readMinutes: 6,
    category: "Food",
  },
  {
    id: "b3",
    slug: "history-of-hargeisa",
    title: "A Short History of Hargeisa",
    excerpt: "How a colonial-era trading post became the capital of Somaliland.",
    coverImage: placeholderImage("History of Hargeisa", { tone: "accent" }),
    author: "Go Hargeisa Editorial",
    publishedAt: "2026-04-30",
    readMinutes: 9,
    category: "Culture",
  },
];

export const mapPoints: MapPoint[] = [
  { id: "m1", name: "Ambassador Hotel", category: "hotel", location: { lat: 9.5624, lng: 44.065 } },
  {
  id: "m2",
  name: "Sultan Restaurant",
  category: "restaurant",
  location: {
    lat: 9.5624,
    lng: 44.0659
  }
},
  { id: "m3", name: "Hargeisa Group Hospital", category: "hospital", location: { lat: 9.5545, lng: 44.0631 } },
  { id: "m4", name: "Dahabshiil Bank HQ", category: "bank", location: { lat: 9.5599, lng: 44.0663 } },
  { id: "m5", name: "Jamia Mosque", category: "mosque", location: { lat: 9.5619, lng: 44.0678 } },
  { id: "m6", name: "Waheen Market", category: "shopping", location: { lat: 9.5598, lng: 44.0705 } },
  { id: "m7", name: "MiG Monument", category: "attraction", location: { lat: 9.5605, lng: 44.065 } },
];

export const HARGEISA_CENTER = { lat: 9.5624, lng: 44.065 };
