import {
  Wifi,
  ParkingSquare,
  Compass,
  UsersRound,
  Umbrella,
  Armchair,
  Snowflake,
  CreditCard,
  Banknote,
  Accessibility,
  PawPrint,
  Cigarette,
  CigaretteOff,
  DoorClosed,
  Presentation,
  Gamepad2,
  ToyBrick,
  Waves,
  Dumbbell,
  Sparkles,
  UtensilsCrossed,
  Sunrise,
  Sun,
  Moon,
  ShoppingBag,
  Truck,
  CarFront,
  CalendarCheck,
  Ticket,
  TicketX,
  UserCheck,
  Camera,
  BatteryCharging,
  Landmark,
  Bath,
  Baby,
  ShieldCheck,
  Video,
  type LucideIcon,
} from "lucide-react";

/**
 * Single fixed vocabulary for the "Amenities" section on every listing
 * detail page (hotels/restaurants/cafes/attractions/events/eligible city
 * services) — replaces hotels' free-text+regex amenities and cafes' own
 * separate fixed-enum amenities, which were two incompatible systems. Icons
 * are resolved from this string code (not passed as a prop) so this file is
 * safe to import from both server and client components — see the RSC
 * serialization note in prior session notes about passing icon components
 * across the server/client boundary.
 *
 * This is deliberately a *new* concept (`amenities_v2` column) alongside
 * each table's existing free-text `amenities` column, which still powers
 * card-preview chips (hotel-card.tsx, premium-hotel-card.tsx) and the
 * hotel search filter (lib/utils/filter-listings.ts getUniqueAmenities) —
 * those are a different, free-text-driven concern and are intentionally
 * left untouched by this unification.
 */
export const AMENITY_CODES = [
  "wifi",
  "parking",
  "prayer_room",
  "family_area",
  "outdoor_seating",
  "indoor_seating",
  "air_conditioning",
  "card_payment",
  "cash_accepted",
  "wheelchair_accessible",
  "pet_friendly",
  "smoking_area",
  "non_smoking_area",
  "private_rooms",
  "meeting_rooms",
  "kids_area",
  "playground",
  "swimming_pool",
  "gym",
  "spa",
  "restaurant",
  "breakfast",
  "lunch",
  "dinner",
  "takeaway",
  "delivery",
  "drive_thru",
  "reservation_required",
  "free_entry",
  "paid_entry",
  "guide_available",
  "photography_allowed",
  "charging_station",
  "atm",
  "restrooms",
  "baby_changing_room",
  "security",
  "cctv",
] as const;

export type AmenityCode = (typeof AMENITY_CODES)[number];

export const AMENITY_ICON: Record<AmenityCode, LucideIcon> = {
  wifi: Wifi,
  parking: ParkingSquare,
  prayer_room: Compass,
  family_area: UsersRound,
  outdoor_seating: Umbrella,
  indoor_seating: Armchair,
  air_conditioning: Snowflake,
  card_payment: CreditCard,
  cash_accepted: Banknote,
  wheelchair_accessible: Accessibility,
  pet_friendly: PawPrint,
  smoking_area: Cigarette,
  non_smoking_area: CigaretteOff,
  private_rooms: DoorClosed,
  meeting_rooms: Presentation,
  kids_area: Gamepad2,
  playground: ToyBrick,
  swimming_pool: Waves,
  gym: Dumbbell,
  spa: Sparkles,
  restaurant: UtensilsCrossed,
  breakfast: Sunrise,
  lunch: Sun,
  dinner: Moon,
  takeaway: ShoppingBag,
  delivery: Truck,
  drive_thru: CarFront,
  reservation_required: CalendarCheck,
  free_entry: Ticket,
  paid_entry: TicketX,
  guide_available: UserCheck,
  photography_allowed: Camera,
  charging_station: BatteryCharging,
  atm: Landmark,
  restrooms: Bath,
  baby_changing_room: Baby,
  security: ShieldCheck,
  cctv: Video,
};

/** Listing types that participate in the unified amenities system. */
export type AmenitiesListingType = "hotel" | "restaurant" | "cafe" | "attraction" | "event" | "city_service";

/**
 * Which codes are offered as choices per listing type — an admin picker for
 * a cafe shouldn't show "Drive-Thru" or "Private Rooms". Deliberately
 * generous per type rather than overly restrictive; owners know their own
 * business better than a hardcoded matrix does.
 */
export const AMENITIES_BY_LISTING_TYPE: Record<AmenitiesListingType, AmenityCode[]> = {
  hotel: [
    "wifi",
    "parking",
    "prayer_room",
    "family_area",
    "air_conditioning",
    "card_payment",
    "cash_accepted",
    "wheelchair_accessible",
    "pet_friendly",
    "smoking_area",
    "non_smoking_area",
    "private_rooms",
    "meeting_rooms",
    "kids_area",
    "playground",
    "swimming_pool",
    "gym",
    "spa",
    "restaurant",
    "breakfast",
    "lunch",
    "dinner",
    "charging_station",
    "restrooms",
    "baby_changing_room",
    "security",
    "cctv",
  ],
  restaurant: [
    "wifi",
    "parking",
    "prayer_room",
    "family_area",
    "outdoor_seating",
    "indoor_seating",
    "air_conditioning",
    "card_payment",
    "cash_accepted",
    "wheelchair_accessible",
    "pet_friendly",
    "smoking_area",
    "non_smoking_area",
    "private_rooms",
    "meeting_rooms",
    "kids_area",
    "breakfast",
    "lunch",
    "dinner",
    "takeaway",
    "delivery",
    "drive_thru",
    "reservation_required",
    "restrooms",
    "baby_changing_room",
    "security",
    "cctv",
  ],
  cafe: [
    "wifi",
    "parking",
    "outdoor_seating",
    "indoor_seating",
    "air_conditioning",
    "card_payment",
    "cash_accepted",
    "wheelchair_accessible",
    "pet_friendly",
    "smoking_area",
    "non_smoking_area",
    "kids_area",
    "breakfast",
    "takeaway",
    "delivery",
    "restrooms",
    "security",
    "cctv",
  ],
  attraction: [
    "parking",
    "prayer_room",
    "family_area",
    "wheelchair_accessible",
    "pet_friendly",
    "kids_area",
    "playground",
    "restaurant",
    "reservation_required",
    "free_entry",
    "paid_entry",
    "guide_available",
    "photography_allowed",
    "atm",
    "restrooms",
    "baby_changing_room",
    "security",
    "cctv",
    "card_payment",
    "cash_accepted",
  ],
  event: [
    "parking",
    "prayer_room",
    "family_area",
    "wheelchair_accessible",
    "kids_area",
    "reservation_required",
    "free_entry",
    "paid_entry",
    "photography_allowed",
    "atm",
    "restrooms",
    "security",
    "cctv",
    "card_payment",
    "cash_accepted",
  ],
  city_service: [
    "wifi",
    "parking",
    "prayer_room",
    "family_area",
    "wheelchair_accessible",
    "kids_area",
    "playground",
    "card_payment",
    "cash_accepted",
    "atm",
    "restrooms",
    "charging_station",
    "security",
    "cctv",
  ],
};

/** Filters arbitrary stored strings down to known codes — defensive against
 * legacy/invalid values that predate this vocabulary or a future rename. */
export function toAmenityCodes(values: string[] | null | undefined): AmenityCode[] {
  if (!values) return [];
  return values.filter((v): v is AmenityCode => (AMENITY_CODES as readonly string[]).includes(v));
}
